dist: xenial

language: go
go:
  - "1.12.x"

go_import_path: github.com/hawell/z42

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - sudo systemctl restart redis-server
  - echo "127.0.0.1 redis" |  sudo tee -a /etc/hosts > /dev/null

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
